### PR TITLE
Example how to add ListView view to adapter programmatically

### PR DESCRIPTION
**Pull request by al11al**
I remember someone mentioned it in issues

### CODE REVIEW

**Comment by pocorall** [comment]
*  I think this is better because it does not use variables, string type identifiers, and it is shorter:

```
def getView(position: Int, convertView: View, parent: ViewGroup): View = {

  class MyItem extends SLinearLayout {
    val stvTitle = new STextView("Title of Location").textSize(26.sp).textColor(Color.BLACK)
    this += new SVerticalLayout {
      this += stvTitle
    }.clickable(false).<<(MATCH_PARENT, 110.dip)
  }

  val view = if(convertView == null) new MyItem() else convertView.asInstanceOf[MyItem]
  view.stvTitle.text = "Hello view"
  
  view
}
```

* I am not sure that `README.md` is the best place to describe this. I designed it to introduce Scaloid features short as possible.

**Comment by pocorall** [comment]
If the view creation is not too frequent, this is even more simple:
```
def getView(position: Int, convertView: View, parent: ViewGroup): View = 
  new SLinearLayout {
     STextView("Title of Location").textSize(26.sp).textColor(Color.BLACK)
  }
```

**Comment by al11al** [comment]
Hi @pocorall 
Of course you are right! :)
I like more your first suggestion because it reuses views as it was thought.
When I got familiar with Scaloid the README.md was the best resource to get info. As for me it became the manual because I think people use it all the time.

**Comment by al11al** [comment]
@pocorall , I was thinking if each view will include 3 buttons, how onClickListener can check which button is clicked? :)

**Comment by pocorall** [comment]
In this way
```
def getView(position: Int, convertView: View, parent: ViewGroup): View = 
  new SLinearLayout {
    SButton("Hello", toast(s"($position, 1)"))
    SButton("every", toast(s"($position, 2)"))
    SButton("body", toast(s"($position, 3)"))
  }
```

**Comment by al11al** [comment]
As I know this will create 3 listeners per each view or I am wrong?

**Comment by pocorall** [comment]
This is off topic on this pull request. It should go to stackoverflow.

**Pull request closed without merging**
